---
galaxy_info:
  role_name: cisco_nxos_upgrade
  namespace: enterprise
  author: Network Operations
  description: Cisco NX-OS firmware upgrade automation
  company: Enterprise Network Management
  license: proprietary
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - networking
    - cisco
    - nxos
    - firmware
    - upgrade

dependencies: []
